name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: ./Pokedex-api
        run: npm install

      - name: Run ESLint
        working-directory: ./Pokedex-api
        run: npm run lint

  format:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: ./Pokedex-api
        run: npm install

      - name: Check Formatting with Prettier
        working-directory: ./Pokedex-api
        run: npm run format:check

  test:
    name: Run All Tests (unit and integration tests)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: ./Pokedex-api
        run: npm install

      # ----------------------------
      # INSTALL MySQL
      # ----------------------------
      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      # ----------------------------
      # START MYSQL
      # ----------------------------
      - name: Start MySQL container
        run: |
          docker run -d \
            --name mysql \
            -e MYSQL_ROOT_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e MYSQL_DATABASE=${{ secrets.DB_NAME }} \
            -p 3306:3306 \
            mysql:8.0

      - name: Wait for MySQL
        run: |
          until mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASSWORD }} -e "SELECT 1"; do
            sleep 2
          done

      # --------------------------
      # RUN TESTS
      # --------------------------
      - name: Run Tests
        working-directory: ./Pokedex-api
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          POKE_API_BASE_URL: ${{ secrets.POKE_API_BASE_URL }}
        run: npm test
